services:
  - type: web
    name: smartdog-backend
    env: docker
    plan: starter
    region: frankfurt
    repo: https://github.com/pvbraguinha/smartdog-backend
    branch: main
    autoDeploy: true
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        value: postgresql://smartdog_db_fnp8_user:0SMTQjMgkWVSii6sUumnTXNfBp8qweKd@dpg-d10v3rm3jp1c739d1ae0-a.internal:5432/smartdog_db_fnp8
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://smartdog-backend.onrender.com
      - key: APP_KEY
        generateValue: true
