databases:
  - name: smartdog-db
    plan: free
    region: frankfurt

services:
  - type: web
    name: smartdog-backend
    env: docker
    plan: starter
    region: frankfurt
    repo: https://github.com/pvbraguinha/smartdog-backend
    branch: main
    autoDeploy: true
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://smartdog-backend-vlm0.onrender.com/
      - key: APP_KEY
        value: base64:CdANHmCLLwnCYV7btlo6V/2qjNJ2ckiwh0fvLrkxjIQ=
      - key: DATABASE_URL
        fromDatabase:
          name: smartdog-db
          property: connectionString
      - key: REPLICATE_API_TOKEN
        value: r8_PHWq6s0NJIHPqmcsngUszPrkoxxd6gH0y9mPq
      - key: REPLICATE_MODEL_VERSION
        value: fermatresearch/sdxl-controlnet-lora:3bb13fe1c33c35987b33792b01b71ed6529d03f165d1c2416375859f09ca9fef