services:
  - type: web
    name: smartdog-backend
    env: docker
    repo: https://github.com/pvbraguinha/smartdog-backend
    branch: main
    plan: starter
    autoDeploy: true
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://smartdog-backend.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          name: smartdog-db
          type: postgres
          property: host
      - key: DB_PORT
        fromService:
          name: smartdog-db
          type: postgres
          property: port
      - key: DB_USERNAME
        fromService:
          name: smartdog-db
          type: postgres
          property: connectionString
      - key: DB_PASSWORD
        fromService:
          name: smartdog-db
          type: postgres
          property: connectionString
      - key: DATABASE_URL
        fromService:
          name: smartdog-db
          type: postgres
          property: connectionString
      - key: APP_KEY
        generateValue: true

databases:
  - name: smartdog-db
    plan: free
    region: frankfurt